name: Deno

on: [push, pull_request]

jobs:
  build:
    name: tests
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: canary

      - name: Run tests
        run: deno test --coverage=./src/tests/coverage_report  ./src/tests/ --allow-net

      - name: Create coverage report
        run:  deno coverage ./src/tests/coverage_report --lcov > coverage_report.lcov

      - name: Upload coverage report
        uses: codecov/codecov-action@v3
        with:
          files: coverage_report.lcov